version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '05:00'
    labels:
      - 'dependencies'
      - 'automerge'
    open-pull-requests-limit: 10
