name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Typecheck
        run: yarn typecheck

      - name: Find unused exports
        run: yarn find-deadcode

      - name: Linting
        run: yarn lint

      - name: Linting Styles
        run: yarn lint:css

      - name: Test
        run: yarn test

      - name: Storybook
        run: yarn build-storybook

      - name: Build
        run: yarn build
